byebye_world:
    path: byebye-world
    defaults: { _controller: CCIRamScoBundle:Yasmina:findumonde }

personne_home:
    path: /
    defaults: { _controller: CCIRamScoBundle:Yasmina:index }

personne_view:
    path: personne/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:view }
    requirements : 
        id: \d+

personne_add:    
    path: personne/add
    defaults: { _controller: CCIRamScoBundle:Yasmina:add }
    
profil:
    path: profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    
accueil:
    path: accueil
    defaults: { _controller: FOSUserBundle:layout }
