byebye_world:
    path: byebye-world
    defaults: { _controller: CCIRamScoBundle:Yasmina:findumonde }

personne_view:
    path: personne/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:view }
    requirements : 
        id: \d+

personne_add:    
    path: personne/add
    defaults: { _controller: CCIRamScoBundle:Yasmina:add }




index:
    path: index
    defaults: { _controller: CCIRamScoBundle:Yasmina:index }
    
accueil:
    path: accueil
    defaults: { _controller: CCIRamScoBundle:Yasmina:indexPerso}

register:
    path: register
    defaults: { _controller: FOSUserBundle:Registration:register}
    
profil:
    path: profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    
adherent:    
    path: adherent
    defaults: { _controller: CCIRamScoBundle:Yasmina:adherent }
